#!/usr/bin/env python3
"""Build assets/data/steel-sections.json for the web section calculator.

The dimension tables on this site are NOT maintained here. They belong to the
Steel Section Calculator app (the SteelCalc repo), which is the single source
of truth: the app ships one JSON file per family under
`assets/data/sections/`, and this script copies those rows verbatim into one
file the browser can fetch in a single request.

Copying, not re-typing, is the point. Every row keeps its own `verified` flag
so the page can badge an unverified size exactly the way the app does, and a
figure on the website can always be traced back to the row the app used.

Usage
-----
    python3 scripts/build_sections.py --app /path/to/SteelCalc

    # default location: a SteelCalc checkout beside this repo
    python3 scripts/build_sections.py

Re-run it after changing any table in the app, then commit the regenerated
JSON. Nothing here edits the app.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import date
from pathlib import Path

# Family key -> (source file, cross-section shape the calculator draws and
# computes, the standard the size list follows). The shape decides which area
# formula runs, so several families share one shape.
FAMILIES: list[dict] = [
    {"key": "ipe", "file": "ipe.json", "shape": "ibeam", "standard": "EN 10365"},
    {"key": "hea", "file": "hea.json", "shape": "ibeam", "standard": "EN 10365"},
    {"key": "heb", "file": "heb.json", "shape": "ibeam", "standard": "EN 10365"},
    {"key": "upn", "file": "upn.json", "shape": "channel", "standard": "EN 10365"},
    {"key": "angle_equal", "file": "angles_equal.json", "shape": "angle", "standard": "EN 10056"},
    {"key": "angle_unequal", "file": "angles_unequal.json", "shape": "angle", "standard": "EN 10056"},
    {"key": "bar_round", "file": "bars_round.json", "shape": "round", "standard": ""},
    {"key": "bar_square", "file": "bars_square.json", "shape": "square", "standard": ""},
    {"key": "bar_hex", "file": "bars_hex.json", "shape": "hex", "standard": ""},
    {"key": "flat", "file": "flats.json", "shape": "flat", "standard": ""},
]

# Dimensions each shape needs, in the order the formula reads them. A row that
# is missing one of these is a data error, not something to paper over at
# runtime, so the build fails loudly here instead of producing a page that
# silently computes a weight from an undefined dimension.
REQUIRED: dict[str, tuple[str, ...]] = {
    "ibeam": ("h", "b", "tw", "tf", "r"),
    "channel": ("h", "b", "tw", "tf", "r"),
    "angle": ("a", "b", "t", "r1", "r2"),
    "round": ("d",),
    "square": ("s",),
    "hex": ("w",),
    "flat": ("width", "thickness"),
}


def app_revision(app_root: Path) -> str:
    """Short commit id of the app checkout, so a built file can be traced."""
    try:
        out = subprocess.run(
            ["git", "-C", str(app_root), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=10, check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


def build(app_root: Path, out_path: Path) -> dict:
    src_dir = app_root / "assets" / "data" / "sections"
    if not src_dir.is_dir():
        raise SystemExit(f"No section tables at {src_dir}. Pass --app <SteelCalc checkout>.")

    families = []
    total = 0
    for fam in FAMILIES:
        rows = json.loads((src_dir / fam["file"]).read_text(encoding="utf-8"))
        needed = REQUIRED[fam["shape"]]
        sizes = []
        for row in rows:
            missing = [k for k in needed if not isinstance(row.get(k), (int, float))]
            if missing:
                raise SystemExit(
                    f"{fam['file']}: {row.get('designation', '?')} is missing {missing}"
                )
            size = {"designation": row["designation"]}
            size.update({k: row[k] for k in needed})
            size["verified"] = bool(row.get("verified", False))
            sizes.append(size)
        total += len(sizes)
        families.append({
            "key": fam["key"],
            "shape": fam["shape"],
            "standard": fam["standard"],
            "sizes": sizes,
        })

    return {
        "meta": {
            "generated": date.today().isoformat(),
            "source": "SteelCalc, assets/data/sections",
            "source_revision": app_revision(app_root),
            "density_kg_m3": 7850,
            "size_count": total,
            "note": (
                "Generated by tools/build_sections.py. Do not edit by hand: "
                "change the table in the app and re-run the script."
            ),
        },
        "families": families,
    }


def main() -> None:
    here = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", type=Path, default=here.parent / "SteelCalc",
                    help="path to the SteelCalc checkout (default: beside this repo)")
    ap.add_argument("--out", type=Path, default=here / "assets" / "data" / "steel-sections.json")
    args = ap.parse_args()

    data = build(args.app.expanduser().resolve(), args.out)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")

    print(f"{args.out}: {data['meta']['size_count']} sizes "
          f"in {len(data['families'])} families "
          f"(app {data['meta']['source_revision']})")


if __name__ == "__main__":
    main()
